In [2]:
import pandas as pd
df = pd.read_csv('newData.csv')
df.head()

,id,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,31112,Male,80.0,0,1,Yes,Private,Rural,105.92,32.50,never smoked,1
1,53882,Male,74.0,1,1,Yes,Private,Rural,70.09,27.40,never smoked,1
2,10434,Female,69.0,0,0,No,Private,Urban,94.39,22.80,never smoked,1
3,27419,Female,59.0,0,0,Yes,Private,Rural,76.15,28.89,Unknown,1
4,60491,Female,78.0,0,0,Yes,Private,Urban,58.57,24.20,Unknown,1

In [3]:
inputs = df.drop(['stroke','id'],axis='columns')
tareget = df['stroke']

In [4]:
inputs

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status
0,Male,80.0,0,1,Yes,Private,Rural,105.92,32.50,never smoked
1,Male,74.0,1,1,Yes,Private,Rural,70.09,27.40,never smoked
2,Female,69.0,0,0,No,Private,Urban,94.39,22.80,never smoked
3,Female,59.0,0,0,Yes,Private,Rural,76.15,28.89,Unknown
4,Female,78.0,0,0,Yes,Private,Urban,58.57,24.20,Unknown
...,...,...,...,...,...,...,...,...,...,...
4343,Female,13.0,0,0,No,children,Rural,103.08,18.60,Unknown
4344,Female,80.0,1,0,Yes,Private,Urban,83.75,28.89,never smoked
4345,Female,81.0,0,0,Yes,Self-employed,Urban,125.20,40.00,never smoked
4346,Female,35.0,0,0,Yes,Self-employed,Rural,82.99,30.60,never smoked
4347,Female,44.0,0,0,Yes,Govt_job,Urban,85.28,26.20,Unknown

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le_gender = LabelEncoder()
le_hypertension = LabelEncoder()
le_heart_disease =  LabelEncoder()
le_ever_married = LabelEncoder()
le_work_type= LabelEncoder()
le_Residence_type = LabelEncoder()
le_smoking_status =  LabelEncoder()

In [7]:
inputs['gender_n'] = le_gender.fit_transform(inputs['gender'])
inputs['age_n'] = inputs['age']
inputs['hypertension_n'] = le_hypertension.fit_transform(inputs['hypertension'])
inputs['heart_disease_n'] = le_heart_disease.fit_transform(inputs['heart_disease'])
inputs['ever_married_n'] = le_ever_married.fit_transform(inputs['ever_married'])
inputs['work_type_n'] = le_work_type.fit_transform(inputs['work_type'])
inputs['Residence_type_n'] = le_Residence_type.fit_transform(inputs['Residence_type'])
inputs['avg_glucose_level_n'] = inputs['avg_glucose_level']
inputs['bmi_n'] = inputs['bmi']
inputs['smoking_status_n'] = le_smoking_status.fit_transform(inputs['smoking_status'])
inputs.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,gender_n,age_n,hypertension_n,heart_disease_n,ever_married_n,work_type_n,Residence_type_n,avg_glucose_level_n,bmi_n,smoking_status_n
0,Male,80.0,0,1,Yes,Private,Rural,105.92,32.50,never smoked,1,80.0,0,1,1,2,0,105.92,32.50,2
1,Male,74.0,1,1,Yes,Private,Rural,70.09,27.40,never smoked,1,74.0,1,1,1,2,0,70.09,27.40,2
2,Female,69.0,0,0,No,Private,Urban,94.39,22.80,never smoked,0,69.0,0,0,0,2,1,94.39,22.80,2
3,Female,59.0,0,0,Yes,Private,Rural,76.15,28.89,Unknown,0,59.0,0,0,1,2,0,76.15,28.89,0
4,Female,78.0,0,0,Yes,Private,Urban,58.57,24.20,Unknown,0,78.0,0,0,1,2,1,58.57,24.20,0

In [8]:
inputs_n = inputs.drop(['gender','hypertension','Residence_type','heart_disease','ever_married','work_type','smoking_status','bmi','avg_glucose_level','age'],axis='columns')
inputs_n

,gender_n,age_n,hypertension_n,heart_disease_n,ever_married_n,work_type_n,Residence_type_n,avg_glucose_level_n,bmi_n,smoking_status_n
0,1,80.0,0,1,1,2,0,105.92,32.50,2
1,1,74.0,1,1,1,2,0,70.09,27.40,2
2,0,69.0,0,0,0,2,1,94.39,22.80,2
3,0,59.0,0,0,1,2,0,76.15,28.89,0
4,0,78.0,0,0,1,2,1,58.57,24.20,0
...,...,...,...,...,...,...,...,...,...,...
4343,0,13.0,0,0,0,4,0,103.08,18.60,0
4344,0,80.0,1,0,1,2,1,83.75,28.89,2
4345,0,81.0,0,0,1,3,1,125.20,40.00,2
4346,0,35.0,0,0,1,3,0,82.99,30.60,2
4347,0,44.0,0,0,1,0,1,85.28,26.20,0

In [10]:
from sklearn import model_selection
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
array = inputs_n.values
X = array[:,0:7]
Y = array[:,8]
testSize = 0.25
kfold = model_selection.KFold(n_splits=20)

In [11]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
cv_results = model_selection.cross_val_score(dtc, X, Y, cv=kfold)
msg = "Mean = %f STD= %f" % (cv_results.mean(), cv_results.std())
print(msg)

Mean = nan STD= nan

/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/multiclass.py", line 183, in check_classification_targets
    raise ValueError("Unknown label type: %r" % y_type)
ValueError: Unknown label type: 'continuous'

  warnings.warn("Estimator fit failed. The score on this train-test"
/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py:610: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details:
Traceback (most recent call last):
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_validation.py", line 593, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 898, in fit
    super().fit(
  File "/Users/ameedal-tamimi/opt/anaconda3/lib/python3.8/site-packages/sklearn/tree/_classes.py", line 190, in fit
    check_classification_targets(y)